model:
  name: RNN-PTB
  initializer_name: random_uniform
  initializer_args:
    minval: -0.05
    maxval: 0.05
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  embedding_size: 600
  cell_type: BasicRNN
  cells:
    - num_units: 600
    - num_units: 600
  loss_func: sequence_loss
  dataset: ptb
train:
  epoch_num: 60
  num_steps: 40
  batch_size: 20
  keep_prob: 0.5
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 1.0
  optimizer: GradientDescent
  learning_rate: "lambda x: 1.0 * (1.0 if x < 7 else (0.9)** (x-7))"

