model:
  name: SHAKESPEARE-2
  initializer_name: random_uniform
  initializer_args:
    minval: -0.04
    maxval: 0.04
  input_dtype: int32
  target_dtype: int32
  vocab_size: 14981
  embedding_size: 1024
  cell_type: BasicLSTM
  cells:
    - num_units: 1024
    - num_units: 1024
  loss_func: sequence_loss
  dataset: shakespeare
train:
  epoch_num: 60
  num_steps: 30
  batch_size: 32
  keep_prob: 0.45
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 15.0
  optimizer: GradientDescent
  learning_rate: "lambda epoch: 2.0 *(1.0 if epoch < 15 else 0.88**(epoch - 15))"
