model:
  name: SHAKESPEARE-GRU-3
  initializer_name: random_uniform
  initializer_args:
    minval: -0.05
    maxval: 0.05
  input_dtype: int32
  target_dtype: int32
  vocab_size: 14981
  embedding_size: 512
  cell_type: GRU
  cells:
    - num_units: 512
    - num_units: 512
    - num_units: 512
    - num_units: 512
  loss_func: sequence_loss
  dataset: shakespeare
train:
  epoch_num: 50
  num_steps: 50
  batch_size: 20
  keep_prob: 0.35
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: Adam
  learning_rate: 0.0002
