model:
  name: SHAKESPEARE
  initializer_name: random_uniform
  initializer_args:
    minval: -0.05
    maxval: 0.05
  input_dtype: int32
  target_dtype: int32
  vocab_size: 14981
  embedding_size: 1000
  cell_type: BasicLSTM
  cells:
    - num_units: 1000
    - num_units: 1000
  loss_func: sequence_loss
  dataset: shakespeare
train:
  epoch_num: 40
  num_steps: 50
  batch_size: 20
  keep_prob: 0.30
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: Adam
  learning_rate: 0.001 
