model:
  name: YELP-2-GRU-50-1
  initializer_name: random_uniform
  initializer_args:
    minval: -0.05
    maxval: 0.05
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  target_size: 2
  use_last_output: True
  embedding_size: 50
  cell_type: GRU
  cells:
    - num_units: 50
  loss_func: sentence_loss
  dataset: yelp-2
train:
  epoch_num: 5
  num_steps: 100
  batch_size: 16
  keep_prob: 1.0
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 1.0
  optimizer: Adam
  learning_rate: 0.001

