model:
  name: YELP-2-GRU-200-1
  initializer_name: random_uniform
  initializer_args:
    minval: -0.05
    maxval: 0.05
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  target_size: 2
  use_last_output: True
  embedding_size: 200
  cell_type: GRU
  cells:
    - num_units: 200
  loss_func: sentence_loss
  dataset: yelp-2
train:
  epoch_num: 15
  num_steps: 100
  batch_size: 32
  keep_prob: 0.5
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 1.0
  optimizer: RMSProp
  learning_rate: 0.001

