model:
  name: IMDB-2
  initializer_name: random_uniform
  initializer_args:
    minval: -0.1
    maxval: 0.1
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  target_size: 2
  use_last_output: True
  embedding_size: 500
  cell_type: BasicLSTM
  cells:
    - num_units: 500
    - num_units: 500
  loss_func: sentence_loss
  dataset: imdb-small
train:
  epoch_num: 20
  num_steps: 500
  batch_size: 200
  keep_prob: 1.0
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 1.0
  optimizer: GradientDescent
  learning_rate: "lambda x: 0.01 * (1.0 if x < 4 else 0.9 ** (x - 4))"
