model:
  name: LSTM-PTB
  initializer_name: random_uniform
  initializer_args:
    minval: -0.1
    maxval: 0.1
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  embedding_size: 400
  cell_type: BasicLSTM
  cells:
    - num_units: 400
    - num_units: 400
  loss_func: sequence_loss
train:
  epoch_num: 40
  num_steps: 40
  batch_size: 20
  keep_prob: 1.0
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: GradientDescent
  learning_rate: "lambda epoch: 1.0 if epoch < 5 else 0.8**(epoch-5)"
