model:
  name: LSTM-PTB
  initializer_name: random_uniform
  initializer_args:
    minval: -0.1
    maxval: 0.1
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  embedding_size: 200
  cell_type: BasicLSTM
  cells:
    - num_units: 200
    - num_units: 200
  loss_func: sequence_loss



