model:
  name: LSTM-SMALL
  initializer_name: random_uniform
  initializer_args:
    minval: -0.1
    maxval: 0.1
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  embedding_size: 50
  cell_type: BasicLSTM
  cells:
    - num_units: 50
    - num_units: 50
  loss_func: sequence_loss
  dataset: tinyshakespeare
train:
  epoch_num: 10
  num_steps: 10
  batch_size: 20
  keep_prob: 1.0
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: GradientDescent
  learning_rate: "lambda epoch: 1.0 if epoch < 4 else 0.6**(epoch-4)"
