#'IMDB':
#  'config': imdb-tiny.yml
'PTB-RNN':
  'config': rnn.yml
#'PTB-GRU':
#  'config': gru.yml
'PTB-LSTM-SMALL':
  'config': lstm-small.yml
'PTB-LSTM-MEDIUM':
  'config': lstm.yml
'PTB-LSTM-LARGE':
  'config': lstm-large.yml
#'YELP-GRU-1000':
#  'config': yelp-gru-1000.yml
#'YELP-GRU-200':
#  'config': yelp-gru-200.yml
#'YELP-GRU-50':
#  'config': yelp-gru-50.yml
#'YELP-LSTM-1000':
#  'config': yelp-lstm-1000.yml
#'YELP-LSTM-50':
#  'config': yelp-2-lstm-200-1.yml
#'YELP-LSTM-50':
#  'config': yelp-lstm-50.yml
#'YELP-RNN-50':
#  'config': yelp-rnn-1000.yml
#'YELP-RNN-50':
#  'config': yelp-rnn-200.yml
#'YELP-RNN-50':
#  'config': yelp-rnn-50.yml
#'PTB-LARGE':
#  'config': lstm-large.yml
'YELP-2-GRU-50-1':
  'config': yelp-2-gru-50-1.yml
'YELP-2-GRU-100-1':
  'config': yelp-2-gru-100-1.yml
'YELP-2-LSTM-100-1':
  'config': yelp-2-lstm-100-1.yml
'Shakespeare-Small':
  'config': shakespeare0.yml
'Shakespeare-Medium':
  'config': shakespeare1.yml
'Shakespeare-Large':
  'config': shakespeare2.yml
#'WMT-Seq2Seq-GRU':
#  'config': wmt-seq2seq-gru.yml
#'WMT-Seq2Seq-GRU2':
#  'config': wmt-seq2seq-gru-2.yml
