model:
  name: SHAKESPEARE-4
  initializer_name: random_uniform
  initializer_args:
    minval: -0.03
    maxval: 0.03
  input_dtype: int32
  target_dtype: int32
  vocab_size: 8000
  embedding_size: 1000
  cell_type: BasicLSTM
  cells:
    - num_units: 1500
    - num_units: 1500
  loss_func: sequence_loss
train:
  epoch_num: 50
  num_steps: 40
  batch_size: 20
  keep_prob: 0.4
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 15.0
  optimizer: Adam
  learning_rate: 0.01
