model:
  name: SHAKESPEARE-2
  initializer_name: random_uniform
  initializer_args:
    minval: -0.05
    maxval: 0.05
  input_dtype: int32
  target_dtype: int32
  vocab_size: 14981
  embedding_size: 1300
  cell_type: BasicLSTM
  cells:
    - num_units: 1300
    - num_units: 1300
  loss_func: sequence_loss
  dataset: shakespeare
train:
  epoch_num: 50
  num_steps: 40
  batch_size: 20
  keep_prob: 0.35
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: GradientDescent
  learning_rate: "lambda epoch: 2.0 *(1.0 if epoch < 9 else 0.9**(epoch - 9))"
