model:
  name: SHAKESPEARE-1
  initializer_name: random_uniform
  initializer_args:
    minval: -0.04
    maxval: 0.04
  input_dtype: int32
  target_dtype: int32
  vocab_size: 14981
  embedding_size: 512
  cell_type: BasicLSTM
  cells:
    - num_units: 512
    - num_units: 512
  loss_func: sequence_loss
  dataset: shakespeare
train:
  epoch_num: 40
  num_steps: 40
  batch_size: 20
  keep_prob: 0.7
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 4.0
  optimizer: GradientDescent
  learning_rate: "lambda epoch: 4.5 *(1.0 if epoch < 6 else 0.8**(epoch - 6))"
