model:
  name: SHAKESPEARE-GRU-1
  initializer_name: random_uniform
  initializer_args:
    minval: -0.06
    maxval: 0.06
  input_dtype: int32
  target_dtype: int32
  vocab_size: 14981
  embedding_size: 512
  cell_type: GRU
  cells:
    - num_units: 512
    - num_units: 512
    - num_units: 512
  loss_func: sequence_loss
  dataset: shakespeare
train:
  epoch_num: 40
  num_steps: 40
  batch_size: 20
  keep_prob: 0.5
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: GradientDescent
  learning_rate: "lambda epoch: 1.0 *(1.0 if epoch < 7 else 0.88**(epoch - 7))"
