model:
  name: yelp-test
  initializer_name: random_uniform
  initializer_args:
    minval: -0.1
    maxval: 0.1
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10001
  target_size: 5
  use_last_output: True
  embedding_size: 500
  cell_type: BasicLSTM
  cells:
    - num_units: 300
    - num_units: 300
  loss_func: sentence_loss
  dataset: yelp-test
train:
  epoch_num: 40
  num_steps: 100
  batch_size: 32
  keep_prob: 0.9
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 1.0
  optimizer: GradientDescent
  learning_rate: "lambda x: 0.5 * (1.0 if x < 4 else 0.9 ** (x - 4))"

